#%RAML 1.0
title: Healthcare Fitness to CRM Process API
version: v1
baseUri: http://localhost:8081/api/
mediaType: application/json


/patients/{id}:
  displayName: Check if Patient(User) is authorized to Fitbit
  uriParameters:
    id:
      type: string|integer
      description: Patient ID
  get:
    responses:
      200:
        body:
          application/json:
            example: !include getPatientById-response.json
  /authorize:
    displayName: Authorize Fitbit user
    get:
      responses:
        302:
    post:
      responses:
        200:
          body:
            application/json: 
             example: !include postPatientAuthorize-response.json
  /unauthorize:
    displayName: Unauthorize Fitbit user
    get:
      responses:
        200:
          body:
            application/json:
              example: !include getPatientUnauthorize-response.json 
  /migrateFitnessData:
    displayName: Update Fitbit devices data together with activity and sleep observations for given patient
    post:
      description: Update Fitbit devices data together with activity and sleep observations for given patient
      queryParameters:
        fromDate:
          type: string
          example: 2016-07-18
          required: true
      responses:
        200:
          body:
            application/json:
              example: !include migrateFitnessData-response.json